default: &default
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  adapter: postgresql
  encoding: unicode

development: 
  <<: *default
  database: rails_project_development

test:
  <<: *default
  database: rails_project_test

production:
  <<: *default
  detabase: rails_project_production
