name: RSpec
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_USER: "runner"
          POSTGRES_HOST_AUTH_METHOD: "trust"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.4
        bundler-cache: true

    - name: Setup Database
      run: bin/rails db:prepare

    - name: Install Webpacker
      run: bin/rails webpacker:install

    - name: Run Webpacker
      run: bin/webpack

    - name: Run Rubocop
      run: bundle exec rubocop

    - name: Run Tests
      run: bundle exec rspec
      env:
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
